name: 'Sops tool installer'
description: 'Install a specific version of sops binary. Acceptable values are latest or any semantic version string like 1.15.0'
inputs: 
  version:
    description: 'Version of sops'
    required: true
    default: 'latest'
outputs:
  sops-path:
    description: 'Path to the cached sops binary'
branding:
  color: 'orange'
runs:
  using: 'node12'
  main: 'lib/run.js'
  